let marks1 = 85;
let marks2 = 92;
let marks3 = 78;
let marks4 = 95;
let highestMarks = Math.max(marks1, marks2, marks3, marks4);
let averageMarks = 87.6;
let randomMarks = Math.floor(Math.random() * 101);
console.log("Random Marks:", randomMarks);
console.log("Rounded Marks:", Math.round(averageMarks));
console.log("Highest Marks:", highestMarks);
